import { Book } from '@/types/bible';

export const BIBLE_BOOKS: Book[] = [
  // 구약 (Old Testament)
  { id: 1, name: 'Genesis', nameKo: '창세기', abbreviation: 'Gen', testament: 'OT', chapters: 50 },
  { id: 2, name: 'Exodus', nameKo: '출애굽기', abbreviation: 'Exo', testament: 'OT', chapters: 40 },
  { id: 3, name: 'Leviticus', nameKo: '레위기', abbreviation: 'Lev', testament: 'OT', chapters: 27 },
  { id: 4, name: 'Numbers', nameKo: '민수기', abbreviation: 'Num', testament: 'OT', chapters: 36 },
  { id: 5, name: 'Deuteronomy', nameKo: '신명기', abbreviation: 'Deu', testament: 'OT', chapters: 34 },
  { id: 6, name: 'Joshua', nameKo: '여호수아', abbreviation: 'Jos', testament: 'OT', chapters: 24 },
  { id: 7, name: 'Judges', nameKo: '사사기', abbreviation: 'Jdg', testament: 'OT', chapters: 21 },
  { id: 8, name: 'Ruth', nameKo: '룻기', abbreviation: 'Rut', testament: 'OT', chapters: 4 },
  { id: 9, name: '1 Samuel', nameKo: '사무엘상', abbreviation: '1Sa', testament: 'OT', chapters: 31 },
  { id: 10, name: '2 Samuel', nameKo: '사무엘하', abbreviation: '2Sa', testament: 'OT', chapters: 24 },
  { id: 11, name: '1 Kings', nameKo: '열왕기상', abbreviation: '1Ki', testament: 'OT', chapters: 22 },
  { id: 12, name: '2 Kings', nameKo: '열왕기하', abbreviation: '2Ki', testament: 'OT', chapters: 25 },
  { id: 13, name: '1 Chronicles', nameKo: '역대상', abbreviation: '1Ch', testament: 'OT', chapters: 29 },
  { id: 14, name: '2 Chronicles', nameKo: '역대하', abbreviation: '2Ch', testament: 'OT', chapters: 36 },
  { id: 15, name: 'Ezra', nameKo: '에스라', abbreviation: 'Ezr', testament: 'OT', chapters: 10 },
  { id: 16, name: 'Nehemiah', nameKo: '느헤미야', abbreviation: 'Neh', testament: 'OT', chapters: 13 },
  { id: 17, name: 'Esther', nameKo: '에스더', abbreviation: 'Est', testament: 'OT', chapters: 10 },
  { id: 18, name: 'Job', nameKo: '욥기', abbreviation: 'Job', testament: 'OT', chapters: 42 },
  { id: 19, name: 'Psalms', nameKo: '시편', abbreviation: 'Psa', testament: 'OT', chapters: 150 },
  { id: 20, name: 'Proverbs', nameKo: '잠언', abbreviation: 'Pro', testament: 'OT', chapters: 31 },
  { id: 21, name: 'Ecclesiastes', nameKo: '전도서', abbreviation: 'Ecc', testament: 'OT', chapters: 12 },
  { id: 22, name: 'Song of Solomon', nameKo: '아가', abbreviation: 'Sng', testament: 'OT', chapters: 8 },
  { id: 23, name: 'Isaiah', nameKo: '이사야', abbreviation: 'Isa', testament: 'OT', chapters: 66 },
  { id: 24, name: 'Jeremiah', nameKo: '예레미야', abbreviation: 'Jer', testament: 'OT', chapters: 52 },
  { id: 25, name: 'Lamentations', nameKo: '예레미야애가', abbreviation: 'Lam', testament: 'OT', chapters: 5 },
  { id: 26, name: 'Ezekiel', nameKo: '에스겔', abbreviation: 'Eze', testament: 'OT', chapters: 48 },
  { id: 27, name: 'Daniel', nameKo: '다니엘', abbreviation: 'Dan', testament: 'OT', chapters: 12 },
  { id: 28, name: 'Hosea', nameKo: '호세아', abbreviation: 'Hos', testament: 'OT', chapters: 14 },
  { id: 29, name: 'Joel', nameKo: '요엘', abbreviation: 'Jol', testament: 'OT', chapters: 3 },
  { id: 30, name: 'Amos', nameKo: '아모스', abbreviation: 'Amo', testament: 'OT', chapters: 9 },
  { id: 31, name: 'Obadiah', nameKo: '오바댜', abbreviation: 'Oba', testament: 'OT', chapters: 1 },
  { id: 32, name: 'Jonah', nameKo: '요나', abbreviation: 'Jon', testament: 'OT', chapters: 4 },
  { id: 33, name: 'Micah', nameKo: '미가', abbreviation: 'Mic', testament: 'OT', chapters: 7 },
  { id: 34, name: 'Nahum', nameKo: '나훔', abbreviation: 'Nam', testament: 'OT', chapters: 3 },
  { id: 35, name: 'Habakkuk', nameKo: '하박국', abbreviation: 'Hab', testament: 'OT', chapters: 3 },
  { id: 36, name: 'Zephaniah', nameKo: '스바냐', abbreviation: 'Zep', testament: 'OT', chapters: 3 },
  { id: 37, name: 'Haggai', nameKo: '학개', abbreviation: 'Hag', testament: 'OT', chapters: 2 },
  { id: 38, name: 'Zechariah', nameKo: '스가랴', abbreviation: 'Zec', testament: 'OT', chapters: 14 },
  { id: 39, name: 'Malachi', nameKo: '말라기', abbreviation: 'Mal', testament: 'OT', chapters: 4 },
  // 신약 (New Testament)
  { id: 40, name: 'Matthew', nameKo: '마태복음', abbreviation: 'Mat', testament: 'NT', chapters: 28 },
  { id: 41, name: 'Mark', nameKo: '마가복음', abbreviation: 'Mrk', testament: 'NT', chapters: 16 },
  { id: 42, name: 'Luke', nameKo: '누가복음', abbreviation: 'Luk', testament: 'NT', chapters: 24 },
  { id: 43, name: 'John', nameKo: '요한복음', abbreviation: 'Jhn', testament: 'NT', chapters: 21 },
  { id: 44, name: 'Acts', nameKo: '사도행전', abbreviation: 'Act', testament: 'NT', chapters: 28 },
  { id: 45, name: 'Romans', nameKo: '로마서', abbreviation: 'Rom', testament: 'NT', chapters: 16 },
  { id: 46, name: '1 Corinthians', nameKo: '고린도전서', abbreviation: '1Co', testament: 'NT', chapters: 16 },
  { id: 47, name: '2 Corinthians', nameKo: '고린도후서', abbreviation: '2Co', testament: 'NT', chapters: 13 },
  { id: 48, name: 'Galatians', nameKo: '갈라디아서', abbreviation: 'Gal', testament: 'NT', chapters: 6 },
  { id: 49, name: 'Ephesians', nameKo: '에베소서', abbreviation: 'Eph', testament: 'NT', chapters: 6 },
  { id: 50, name: 'Philippians', nameKo: '빌립보서', abbreviation: 'Php', testament: 'NT', chapters: 4 },
  { id: 51, name: 'Colossians', nameKo: '골로새서', abbreviation: 'Col', testament: 'NT', chapters: 4 },
  { id: 52, name: '1 Thessalonians', nameKo: '데살로니가전서', abbreviation: '1Th', testament: 'NT', chapters: 5 },
  { id: 53, name: '2 Thessalonians', nameKo: '데살로니가후서', abbreviation: '2Th', testament: 'NT', chapters: 3 },
  { id: 54, name: '1 Timothy', nameKo: '디모데전서', abbreviation: '1Ti', testament: 'NT', chapters: 6 },
  { id: 55, name: '2 Timothy', nameKo: '디모데후서', abbreviation: '2Ti', testament: 'NT', chapters: 4 },
  { id: 56, name: 'Titus', nameKo: '디도서', abbreviation: 'Tit', testament: 'NT', chapters: 3 },
  { id: 57, name: 'Philemon', nameKo: '빌레몬서', abbreviation: 'Phm', testament: 'NT', chapters: 1 },
  { id: 58, name: 'Hebrews', nameKo: '히브리서', abbreviation: 'Heb', testament: 'NT', chapters: 13 },
  { id: 59, name: 'James', nameKo: '야고보서', abbreviation: 'Jas', testament: 'NT', chapters: 5 },
  { id: 60, name: '1 Peter', nameKo: '베드로전서', abbreviation: '1Pe', testament: 'NT', chapters: 5 },
  { id: 61, name: '2 Peter', nameKo: '베드로후서', abbreviation: '2Pe', testament: 'NT', chapters: 3 },
  { id: 62, name: '1 John', nameKo: '요한일서', abbreviation: '1Jn', testament: 'NT', chapters: 5 },
  { id: 63, name: '2 John', nameKo: '요한이서', abbreviation: '2Jn', testament: 'NT', chapters: 1 },
  { id: 64, name: '3 John', nameKo: '요한삼서', abbreviation: '3Jn', testament: 'NT', chapters: 1 },
  { id: 65, name: 'Jude', nameKo: '유다서', abbreviation: 'Jud', testament: 'NT', chapters: 1 },
  { id: 66, name: 'Revelation', nameKo: '요한계시록', abbreviation: 'Rev', testament: 'NT', chapters: 22 },
];

export const SUPPORTED_VERSIONS: { id: string; name: string; language: string }[] = [
  { id: 'krv', name: '개역한글', language: 'ko' },
  { id: 'kjv', name: 'King James Version', language: 'en' },
  { id: 'web', name: 'World English Bible', language: 'en' },
];

// Map our version IDs to the API's translation IDs
export const VERSION_MAP: Record<string, string> = {
  krv: 'kor_old',
  kjv: 'eng_kjv',
  web: 'ENGWEBP',
  bsb: 'BSB',
};

// Book name to API book ID mapping (3-letter codes)
export const BOOK_ID_MAP: Record<string, string> = {
  'Genesis': 'GEN', 'Exodus': 'EXO', 'Leviticus': 'LEV', 'Numbers': 'NUM',
  'Deuteronomy': 'DEU', 'Joshua': 'JOS', 'Judges': 'JDG', 'Ruth': 'RUT',
  '1 Samuel': '1SA', '2 Samuel': '2SA', '1 Kings': '1KI', '2 Kings': '2KI',
  '1 Chronicles': '1CH', '2 Chronicles': '2CH', 'Ezra': 'EZR', 'Nehemiah': 'NEH',
  'Esther': 'EST', 'Job': 'JOB', 'Psalms': 'PSA', 'Proverbs': 'PRO',
  'Ecclesiastes': 'ECC', 'Song of Solomon': 'SNG', 'Isaiah': 'ISA', 'Jeremiah': 'JER',
  'Lamentations': 'LAM', 'Ezekiel': 'EZK', 'Daniel': 'DAN', 'Hosea': 'HOS',
  'Joel': 'JOL', 'Amos': 'AMO', 'Obadiah': 'OBA', 'Jonah': 'JON',
  'Micah': 'MIC', 'Nahum': 'NAM', 'Habakkuk': 'HAB', 'Zephaniah': 'ZEP',
  'Haggai': 'HAG', 'Zechariah': 'ZEC', 'Malachi': 'MAL',
  'Matthew': 'MAT', 'Mark': 'MRK', 'Luke': 'LUK', 'John': 'JHN',
  'Acts': 'ACT', 'Romans': 'ROM', '1 Corinthians': '1CO', '2 Corinthians': '2CO',
  'Galatians': 'GAL', 'Ephesians': 'EPH', 'Philippians': 'PHP', 'Colossians': 'COL',
  '1 Thessalonians': '1TH', '2 Thessalonians': '2TH', '1 Timothy': '1TI', '2 Timothy': '2TI',
  'Titus': 'TIT', 'Philemon': 'PHM', 'Hebrews': 'HEB', 'James': 'JAS',
  '1 Peter': '1PE', '2 Peter': '2PE', '1 John': '1JN', '2 John': '2JN',
  '3 John': '3JN', 'Jude': 'JUD', 'Revelation': 'REV',
};
