export interface BiblicalPlace {
  id: string;
  name: string;
  nameKo: string;
  lat: number;
  lng: number;
  description: string;
  descriptionKo: string;
  books: number[];
  type: 'city' | 'mountain' | 'river' | 'sea' | 'region' | 'other';
}

export const BIBLICAL_PLACES: BiblicalPlace[] = [
  // === Cities ===
  {
    id: 'jerusalem',
    name: 'Jerusalem',
    nameKo: '예루살렘',
    lat: 31.7683,
    lng: 35.2137,
    description: 'Holy city, capital of ancient Israel, site of Solomon\'s Temple and Jesus\' crucifixion.',
    descriptionKo: '거룩한 도시, 고대 이스라엘의 수도, 솔로몬 성전과 예수님의 십자가 처형 장소.',
    books: [6, 9, 10, 11, 12, 13, 14, 15, 16, 19, 23, 24, 26, 27, 40, 41, 42, 43, 44, 66],
    type: 'city',
  },
  {
    id: 'bethlehem',
    name: 'Bethlehem',
    nameKo: '베들레헴',
    lat: 31.7054,
    lng: 35.2024,
    description: 'Birthplace of Jesus Christ and King David.',
    descriptionKo: '예수 그리스도와 다윗 왕의 출생지.',
    books: [1, 8, 9, 33, 40, 42],
    type: 'city',
  },
  {
    id: 'nazareth',
    name: 'Nazareth',
    nameKo: '나사렛',
    lat: 32.6996,
    lng: 35.3035,
    description: 'Hometown of Jesus where He grew up.',
    descriptionKo: '예수님이 자라신 고향.',
    books: [40, 41, 42, 43],
    type: 'city',
  },
  {
    id: 'capernaum',
    name: 'Capernaum',
    nameKo: '가버나움',
    lat: 32.8803,
    lng: 35.5751,
    description: 'Center of Jesus\' ministry in Galilee.',
    descriptionKo: '갈릴리에서 예수님 사역의 중심지.',
    books: [40, 41, 42, 43],
    type: 'city',
  },
  {
    id: 'jericho',
    name: 'Jericho',
    nameKo: '여리고',
    lat: 31.8611,
    lng: 35.4503,
    description: 'Ancient city conquered by Joshua; site of Jesus healing blind Bartimaeus.',
    descriptionKo: '여호수아가 정복한 고대 도시; 예수님이 소경 바디매오를 고치신 곳.',
    books: [4, 5, 6, 11, 12, 40, 41, 42],
    type: 'city',
  },
  {
    id: 'babylon',
    name: 'Babylon',
    nameKo: '바벨론',
    lat: 32.5363,
    lng: 44.4209,
    description: 'Capital of the Babylonian Empire; place of Jewish exile.',
    descriptionKo: '바벨론 제국의 수도; 유대인 포로 생활의 장소.',
    books: [1, 12, 23, 24, 25, 26, 27, 66],
    type: 'city',
  },
  {
    id: 'nineveh',
    name: 'Nineveh',
    nameKo: '니느웨',
    lat: 36.3598,
    lng: 43.1530,
    description: 'Capital of the Assyrian Empire; destination of Jonah\'s prophecy.',
    descriptionKo: '앗시리아 제국의 수도; 요나의 예언 대상 도시.',
    books: [1, 12, 32, 34],
    type: 'city',
  },
  {
    id: 'antioch-syria',
    name: 'Antioch (Syria)',
    nameKo: '안디옥 (시리아)',
    lat: 36.2021,
    lng: 36.1606,
    description: 'Where believers were first called Christians; base for Paul\'s missions.',
    descriptionKo: '신자들이 처음으로 그리스도인이라 불린 곳; 바울 선교의 기지.',
    books: [44, 48],
    type: 'city',
  },
  {
    id: 'rome',
    name: 'Rome',
    nameKo: '로마',
    lat: 41.9028,
    lng: 12.4964,
    description: 'Capital of the Roman Empire; Paul wrote his epistle to believers here.',
    descriptionKo: '로마 제국의 수도; 바울이 이곳의 성도들에게 서신을 보냄.',
    books: [44, 45, 55],
    type: 'city',
  },
  {
    id: 'corinth',
    name: 'Corinth',
    nameKo: '고린도',
    lat: 37.9057,
    lng: 22.8765,
    description: 'Greek city where Paul established a church and wrote epistles.',
    descriptionKo: '바울이 교회를 세우고 서신을 보낸 그리스 도시.',
    books: [44, 46, 47],
    type: 'city',
  },
  {
    id: 'ephesus',
    name: 'Ephesus',
    nameKo: '에베소',
    lat: 37.9411,
    lng: 27.3420,
    description: 'Major city in Asia Minor; one of the seven churches in Revelation.',
    descriptionKo: '소아시아의 주요 도시; 요한계시록의 일곱 교회 중 하나.',
    books: [44, 49, 54, 55, 66],
    type: 'city',
  },
  {
    id: 'philippi',
    name: 'Philippi',
    nameKo: '빌립보',
    lat: 41.0143,
    lng: 24.2871,
    description: 'First European city where Paul preached; recipient of Paul\'s epistle.',
    descriptionKo: '바울이 복음을 전한 유럽 최초의 도시; 바울 서신의 수신지.',
    books: [44, 50],
    type: 'city',
  },
  {
    id: 'thessalonica',
    name: 'Thessalonica',
    nameKo: '데살로니가',
    lat: 40.6401,
    lng: 22.9444,
    description: 'Greek city where Paul founded a church.',
    descriptionKo: '바울이 교회를 세운 그리스 도시.',
    books: [44, 52, 53],
    type: 'city',
  },
  {
    id: 'athens',
    name: 'Athens',
    nameKo: '아덴',
    lat: 37.9838,
    lng: 23.7275,
    description: 'Greek capital where Paul preached at the Areopagus.',
    descriptionKo: '바울이 아레오바고에서 설교한 그리스 수도.',
    books: [44, 52],
    type: 'city',
  },
  {
    id: 'damascus',
    name: 'Damascus',
    nameKo: '다메섹',
    lat: 33.5138,
    lng: 36.2765,
    description: 'Where Saul (Paul) had his conversion experience on the road.',
    descriptionKo: '사울(바울)이 회심한 도로가 있는 도시.',
    books: [1, 10, 11, 12, 23, 24, 26, 30, 44, 47, 48],
    type: 'city',
  },
  {
    id: 'tyre',
    name: 'Tyre',
    nameKo: '두로',
    lat: 33.2705,
    lng: 35.1958,
    description: 'Ancient Phoenician port city mentioned by prophets.',
    descriptionKo: '선지자들이 언급한 고대 페니키아 항구 도시.',
    books: [6, 10, 11, 23, 24, 26, 29, 30, 38, 40, 41, 44],
    type: 'city',
  },
  {
    id: 'sidon',
    name: 'Sidon',
    nameKo: '시돈',
    lat: 33.5571,
    lng: 35.3729,
    description: 'Ancient Phoenician coastal city north of Tyre.',
    descriptionKo: '두로 북쪽의 고대 페니키아 해안 도시.',
    books: [1, 6, 7, 11, 23, 24, 26, 29, 40, 41, 42, 44],
    type: 'city',
  },
  {
    id: 'bethany',
    name: 'Bethany',
    nameKo: '베다니',
    lat: 31.7700,
    lng: 35.2573,
    description: 'Home of Mary, Martha, and Lazarus; where Jesus raised Lazarus.',
    descriptionKo: '마리아, 마르다, 나사로의 집; 예수님이 나사로를 살리신 곳.',
    books: [40, 41, 42, 43],
    type: 'city',
  },
  {
    id: 'samaria',
    name: 'Samaria',
    nameKo: '사마리아',
    lat: 32.2747,
    lng: 35.1903,
    description: 'Capital of the northern kingdom of Israel.',
    descriptionKo: '북이스라엘 왕국의 수도.',
    books: [11, 12, 23, 24, 26, 28, 30, 33, 43, 44],
    type: 'city',
  },
  {
    id: 'hebron',
    name: 'Hebron',
    nameKo: '헤브론',
    lat: 31.5326,
    lng: 35.0998,
    description: 'City of Abraham; David\'s first capital.',
    descriptionKo: '아브라함의 도시; 다윗의 첫 번째 수도.',
    books: [1, 4, 6, 9, 10, 13],
    type: 'city',
  },
  {
    id: 'beersheba',
    name: 'Beersheba',
    nameKo: '브엘세바',
    lat: 31.2589,
    lng: 34.7913,
    description: 'Southern boundary of Israel; associated with Abraham and Isaac.',
    descriptionKo: '이스라엘의 남쪽 경계; 아브라함과 이삭과 관련된 곳.',
    books: [1, 6, 7, 9, 11, 30],
    type: 'city',
  },
  {
    id: 'shechem',
    name: 'Shechem',
    nameKo: '세겜',
    lat: 32.2141,
    lng: 35.2823,
    description: 'Important patriarchal site; place of covenant renewal.',
    descriptionKo: '중요한 족장시대의 장소; 언약 갱신의 장소.',
    books: [1, 6, 7, 11],
    type: 'city',
  },
  {
    id: 'dan',
    name: 'Dan',
    nameKo: '단',
    lat: 33.2493,
    lng: 35.6520,
    description: 'Northernmost city of Israel; "from Dan to Beersheba".',
    descriptionKo: '이스라엘의 최북단 도시; "단에서 브엘세바까지".',
    books: [1, 6, 7, 9, 10, 11, 12],
    type: 'city',
  },
  {
    id: 'gaza',
    name: 'Gaza',
    nameKo: '가사',
    lat: 31.5017,
    lng: 34.4668,
    description: 'Philistine city associated with Samson.',
    descriptionKo: '삼손과 관련된 블레셋 도시.',
    books: [1, 6, 7, 9, 12, 24, 30, 36, 38, 44],
    type: 'city',
  },
  {
    id: 'laodicea',
    name: 'Laodicea',
    nameKo: '라오디게아',
    lat: 37.8358,
    lng: 29.1081,
    description: 'One of the seven churches in Revelation; known for being lukewarm.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 미지근한 것으로 알려짐.',
    books: [51, 66],
    type: 'city',
  },
  {
    id: 'smyrna',
    name: 'Smyrna',
    nameKo: '서머나',
    lat: 38.4189,
    lng: 27.1287,
    description: 'One of the seven churches in Revelation; suffering persecution.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 핍박을 받는 교회.',
    books: [66],
    type: 'city',
  },
  {
    id: 'pergamum',
    name: 'Pergamum',
    nameKo: '버가모',
    lat: 39.1217,
    lng: 27.1840,
    description: 'One of the seven churches in Revelation; where Satan\'s throne is.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 사단의 보좌가 있는 곳.',
    books: [66],
    type: 'city',
  },
  {
    id: 'thyatira',
    name: 'Thyatira',
    nameKo: '두아디라',
    lat: 38.9197,
    lng: 27.8375,
    description: 'One of the seven churches in Revelation; home of Lydia.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 루디아의 고향.',
    books: [44, 66],
    type: 'city',
  },
  {
    id: 'sardis',
    name: 'Sardis',
    nameKo: '사데',
    lat: 38.4896,
    lng: 28.0400,
    description: 'One of the seven churches in Revelation; spiritually dead.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 영적으로 죽은 교회.',
    books: [66],
    type: 'city',
  },
  {
    id: 'philadelphia',
    name: 'Philadelphia',
    nameKo: '빌라델비아',
    lat: 38.4510,
    lng: 28.3944,
    description: 'One of the seven churches in Revelation; faithful church.',
    descriptionKo: '요한계시록의 일곱 교회 중 하나; 신실한 교회.',
    books: [66],
    type: 'city',
  },
  {
    id: 'ur',
    name: 'Ur of the Chaldeans',
    nameKo: '갈대아 우르',
    lat: 30.9628,
    lng: 46.1031,
    description: 'Abraham\'s original homeland in Mesopotamia.',
    descriptionKo: '메소포타미아에 있는 아브라함의 원래 고향.',
    books: [1, 16],
    type: 'city',
  },
  {
    id: 'haran',
    name: 'Haran',
    nameKo: '하란',
    lat: 36.8633,
    lng: 39.0303,
    description: 'City where Abraham settled before going to Canaan.',
    descriptionKo: '아브라함이 가나안으로 가기 전에 정착한 도시.',
    books: [1, 12],
    type: 'city',
  },
  {
    id: 'cana',
    name: 'Cana',
    nameKo: '가나',
    lat: 32.7475,
    lng: 35.3441,
    description: 'Where Jesus performed His first miracle, turning water into wine.',
    descriptionKo: '예수님이 물을 포도주로 바꾸신 첫 번째 기적을 행하신 곳.',
    books: [43],
    type: 'city',
  },
  {
    id: 'caesarea',
    name: 'Caesarea',
    nameKo: '가이사랴',
    lat: 32.5000,
    lng: 34.8900,
    description: 'Roman administrative capital; where Cornelius was converted.',
    descriptionKo: '로마 행정 수도; 고넬료가 회심한 곳.',
    books: [44],
    type: 'city',
  },
  {
    id: 'caesarea-philippi',
    name: 'Caesarea Philippi',
    nameKo: '가이사랴 빌립보',
    lat: 33.2483,
    lng: 35.6936,
    description: 'Where Peter confessed Jesus as the Christ.',
    descriptionKo: '베드로가 예수님을 그리스도라고 고백한 곳.',
    books: [40, 41],
    type: 'city',
  },
  {
    id: 'antioch-pisidia',
    name: 'Antioch (Pisidia)',
    nameKo: '비시디아 안디옥',
    lat: 38.3015,
    lng: 31.1966,
    description: 'City in Asia Minor visited by Paul on his first missionary journey.',
    descriptionKo: '바울이 첫 번째 선교 여행 중 방문한 소아시아 도시.',
    books: [44, 55],
    type: 'city',
  },
  {
    id: 'colossae',
    name: 'Colossae',
    nameKo: '골로새',
    lat: 37.7879,
    lng: 29.2611,
    description: 'City in Asia Minor; recipient of Paul\'s epistle to the Colossians.',
    descriptionKo: '소아시아의 도시; 바울의 골로새서의 수신지.',
    books: [51],
    type: 'city',
  },
  {
    id: 'patmos',
    name: 'Patmos',
    nameKo: '밧모',
    lat: 37.3216,
    lng: 26.5474,
    description: 'Island where John received the Revelation.',
    descriptionKo: '요한이 계시를 받은 섬.',
    books: [66],
    type: 'city',
  },
  // === Mountains ===
  {
    id: 'mount-sinai',
    name: 'Mount Sinai',
    nameKo: '시내산',
    lat: 28.5390,
    lng: 33.9750,
    description: 'Where God gave Moses the Ten Commandments.',
    descriptionKo: '하나님이 모세에게 십계명을 주신 곳.',
    books: [2, 3, 4, 5, 11, 16, 19, 48],
    type: 'mountain',
  },
  {
    id: 'mount-ararat',
    name: 'Mount Ararat',
    nameKo: '아라랏산',
    lat: 39.7019,
    lng: 44.2991,
    description: 'Where Noah\'s ark came to rest after the flood.',
    descriptionKo: '홍수 후 노아의 방주가 머문 곳.',
    books: [1],
    type: 'mountain',
  },
  {
    id: 'mount-carmel',
    name: 'Mount Carmel',
    nameKo: '갈멜산',
    lat: 32.7414,
    lng: 35.0413,
    description: 'Where Elijah confronted the prophets of Baal.',
    descriptionKo: '엘리야가 바알의 선지자들과 대결한 곳.',
    books: [11, 12, 22, 23, 24, 30, 33, 34],
    type: 'mountain',
  },
  {
    id: 'mount-hermon',
    name: 'Mount Hermon',
    nameKo: '헤르몬산',
    lat: 33.4167,
    lng: 35.8571,
    description: 'Highest mountain in Israel; possible site of Transfiguration.',
    descriptionKo: '이스라엘에서 가장 높은 산; 변화산으로 추정되는 곳.',
    books: [5, 6, 19, 22],
    type: 'mountain',
  },
  {
    id: 'mount-tabor',
    name: 'Mount Tabor',
    nameKo: '다볼산',
    lat: 32.6871,
    lng: 35.3929,
    description: 'Traditional site of the Transfiguration; Barak assembled troops here.',
    descriptionKo: '변화산의 전통적인 장소; 바락이 군대를 소집한 곳.',
    books: [6, 7, 19, 24, 28],
    type: 'mountain',
  },
  {
    id: 'mount-olivet',
    name: 'Mount of Olives',
    nameKo: '감람산',
    lat: 31.7781,
    lng: 35.2453,
    description: 'Where Jesus gave the Olivet Discourse and ascended to heaven.',
    descriptionKo: '예수님이 감람산 설교를 하시고 승천하신 곳.',
    books: [10, 26, 38, 40, 41, 42, 43, 44],
    type: 'mountain',
  },
  {
    id: 'mount-zion',
    name: 'Mount Zion',
    nameKo: '시온산',
    lat: 31.7719,
    lng: 35.2286,
    description: 'Hill in Jerusalem symbolizing God\'s holy city.',
    descriptionKo: '하나님의 거룩한 도시를 상징하는 예루살렘의 언덕.',
    books: [10, 11, 19, 23, 29, 31, 33, 58, 66],
    type: 'mountain',
  },
  {
    id: 'mount-nebo',
    name: 'Mount Nebo',
    nameKo: '느보산',
    lat: 31.7673,
    lng: 35.7254,
    description: 'Where Moses viewed the Promised Land before his death.',
    descriptionKo: '모세가 죽기 전에 약속의 땅을 바라본 곳.',
    books: [4, 5],
    type: 'mountain',
  },
  {
    id: 'mount-moriah',
    name: 'Mount Moriah',
    nameKo: '모리아산',
    lat: 31.7780,
    lng: 35.2354,
    description: 'Where Abraham was told to sacrifice Isaac; site of Solomon\'s Temple.',
    descriptionKo: '아브라함이 이삭을 바치라는 명령을 받은 곳; 솔로몬 성전 터.',
    books: [1, 14],
    type: 'mountain',
  },
  // === Rivers ===
  {
    id: 'jordan-river',
    name: 'Jordan River',
    nameKo: '요단강',
    lat: 32.0000,
    lng: 35.5500,
    description: 'River where Jesus was baptized; Israel crossed into the Promised Land.',
    descriptionKo: '예수님이 세례를 받으신 강; 이스라엘이 약속의 땅으로 건넌 강.',
    books: [1, 4, 5, 6, 7, 9, 10, 11, 12, 40, 41, 42, 43],
    type: 'river',
  },
  {
    id: 'nile-river',
    name: 'Nile River',
    nameKo: '나일강',
    lat: 30.0444,
    lng: 31.2357,
    description: 'Great river of Egypt; Moses was found in a basket here.',
    descriptionKo: '이집트의 대하; 모세가 바구니에서 발견된 곳.',
    books: [1, 2, 23, 24, 26, 30],
    type: 'river',
  },
  {
    id: 'euphrates-river',
    name: 'Euphrates River',
    nameKo: '유프라테스강',
    lat: 34.8500,
    lng: 40.7000,
    description: 'One of the four rivers from Eden; boundary of the Promised Land.',
    descriptionKo: '에덴에서 흐른 네 강 중 하나; 약속의 땅의 경계.',
    books: [1, 5, 6, 10, 11, 12, 24, 66],
    type: 'river',
  },
  {
    id: 'tigris-river',
    name: 'Tigris River',
    nameKo: '티그리스강',
    lat: 35.4681,
    lng: 43.2800,
    description: 'One of the four rivers from Eden; flows through Mesopotamia.',
    descriptionKo: '에덴에서 흐른 네 강 중 하나; 메소포타미아를 관통하여 흐르는 강.',
    books: [1, 27],
    type: 'river',
  },
  // === Seas ===
  {
    id: 'sea-of-galilee',
    name: 'Sea of Galilee',
    nameKo: '갈릴리 바다',
    lat: 32.8200,
    lng: 35.5833,
    description: 'Freshwater lake where Jesus walked on water and calmed the storm.',
    descriptionKo: '예수님이 물 위를 걸으시고 폭풍을 잠잠하게 하신 담수호.',
    books: [4, 6, 40, 41, 42, 43],
    type: 'sea',
  },
  {
    id: 'dead-sea',
    name: 'Dead Sea',
    nameKo: '사해',
    lat: 31.5000,
    lng: 35.5000,
    description: 'Lowest point on earth; near the destroyed cities of Sodom and Gomorrah.',
    descriptionKo: '지구상에서 가장 낮은 곳; 멸망된 소돔과 고모라 근처.',
    books: [1, 4, 5, 6, 26],
    type: 'sea',
  },
  {
    id: 'red-sea',
    name: 'Red Sea',
    nameKo: '홍해',
    lat: 27.5000,
    lng: 34.5000,
    description: 'Sea that God parted for the Israelites to cross during the Exodus.',
    descriptionKo: '출애굽 때 하나님이 이스라엘 백성을 위해 갈라주신 바다.',
    books: [2, 4, 5, 6, 7, 11, 16, 19, 23, 24, 44, 58],
    type: 'sea',
  },
  {
    id: 'mediterranean-sea',
    name: 'Mediterranean Sea',
    nameKo: '지중해',
    lat: 34.0000,
    lng: 30.0000,
    description: 'Called the Great Sea in the Bible; bordered the western edge of Israel.',
    descriptionKo: '성경에서 큰 바다로 불림; 이스라엘의 서쪽 경계.',
    books: [4, 5, 6, 26, 32, 44],
    type: 'sea',
  },
  // === Regions ===
  {
    id: 'goshen',
    name: 'Goshen (Egypt)',
    nameKo: '고센 (이집트)',
    lat: 30.7833,
    lng: 31.8333,
    description: 'Region in Egypt where the Israelites lived before the Exodus.',
    descriptionKo: '출애굽 전에 이스라엘 백성이 살았던 이집트 지역.',
    books: [1, 2],
    type: 'region',
  },
  {
    id: 'galilee',
    name: 'Galilee',
    nameKo: '갈릴리',
    lat: 32.7500,
    lng: 35.3500,
    description: 'Northern region of Israel; center of Jesus\' ministry.',
    descriptionKo: '이스라엘 북부 지역; 예수님 사역의 중심지.',
    books: [6, 11, 12, 23, 40, 41, 42, 43, 44],
    type: 'region',
  },
  {
    id: 'judea',
    name: 'Judea',
    nameKo: '유대',
    lat: 31.5000,
    lng: 35.2000,
    description: 'Southern region of Israel; includes Jerusalem and Bethlehem.',
    descriptionKo: '이스라엘 남부 지역; 예루살렘과 베들레헴을 포함.',
    books: [15, 16, 40, 41, 42, 43, 44],
    type: 'region',
  },
  {
    id: 'canaan',
    name: 'Canaan',
    nameKo: '가나안',
    lat: 32.0000,
    lng: 35.0000,
    description: 'The Promised Land given to Abraham and his descendants.',
    descriptionKo: '아브라함과 그의 후손에게 주어진 약속의 땅.',
    books: [1, 2, 4, 5, 6, 7],
    type: 'region',
  },
  {
    id: 'edom',
    name: 'Edom',
    nameKo: '에돔',
    lat: 30.5000,
    lng: 35.4000,
    description: 'Territory of Esau\'s descendants, southeast of the Dead Sea.',
    descriptionKo: '에서의 후손들의 영토, 사해 남동쪽.',
    books: [1, 4, 5, 6, 9, 10, 11, 12, 23, 24, 25, 26, 29, 30, 31, 33],
    type: 'region',
  },
  {
    id: 'moab',
    name: 'Moab',
    nameKo: '모압',
    lat: 31.4000,
    lng: 35.7000,
    description: 'Territory east of the Dead Sea; homeland of Ruth.',
    descriptionKo: '사해 동쪽의 영토; 룻의 고향.',
    books: [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 23, 24, 25, 36],
    type: 'region',
  },
  // === Other ===
  {
    id: 'garden-of-eden',
    name: 'Garden of Eden',
    nameKo: '에덴동산',
    lat: 32.0000,
    lng: 45.0000,
    description: 'Paradise where God placed Adam and Eve.',
    descriptionKo: '하나님이 아담과 하와를 두신 낙원.',
    books: [1, 23, 26],
    type: 'other',
  },
  {
    id: 'golgotha',
    name: 'Golgotha (Calvary)',
    nameKo: '골고다 (갈보리)',
    lat: 31.7789,
    lng: 35.2298,
    description: 'Place of Jesus\' crucifixion outside Jerusalem.',
    descriptionKo: '예루살렘 성 밖에서 예수님이 십자가에 못 박히신 곳.',
    books: [40, 41, 42, 43],
    type: 'other',
  },
];
